//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForexRateWebAPI.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForexRate
    {
        public System.DateTime Date { get; set; }
        public string Ccy { get; set; }
        public Nullable<decimal> Cash_Buy { get; set; }
        public Nullable<decimal> Cash_Sell { get; set; }
        public Nullable<decimal> Spot_Buy { get; set; }
        public Nullable<decimal> Spot_Sell { get; set; }
    }
}
